### ISSUE TITLE
Fix dependency

### ISSUE THREAD

**Issue by cwkx** [DerelictOrg/DerelictCL#1]
Selected package derelict-util 1.9.1 does not match the dependency specification >=2.0.0 <3.0.0 in package derelict-cl. e.g. change to:  "derelict-util": ">=1.0.3" in dub.json

**Comment by p0nce** [comment]
What other package do you use that demands derelict-util 1.9.1?

Two solution for you:
- use DerelictCL v1.2.3, this is the last tag using DerelictUtil 1.x.y
- fix the other package so that it uses DerelictUtil 2.x.y

**Comment by cwkx** [comment]
I was using:

```
"derelict-gl3": "~>1.0.13",
"derelict-cl": "~>2.0.0",
"derelict-glfw3": "~>1.1.0",
"derelict-imgui": "~>0.3.0",
```

-does this mean I always need to see that warning, or use version 1.2.3? thanks

**Comment by p0nce** [comment]
You can use only one version of derelict-util at once. It will be either DerelictUtil 1.x.y or DerelictUtil 2.x.y
- derelict-cl support both in different versions.
- derelict-gl3 only support the latest derelict-util since using >=.
- same with derelict-glfw3, it uses >=
- but not derelict-imgui: https://github.com/Extrawurst/DerelictImgui/blob/master/dub.json

The best DerelictUtil to choose is thus the latest, DerelictUtil 2.x.y.

The best you can do is post an issue in DerelictImgui asking to issue a new major version using DerelictUtil 2.x.y instead of ~>1.9.1

This is not a derelict-cl problem.

**Comment by cwkx** [comment]
thanks so much for clearing this up, will ask derelict-imgui - cheers
